2022-06-08 20:41:39,469 - ERROR - task.py - <module> - 33 - division by zero
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 20:43:23,788 - ERROR - task.py - <module> - 33 - ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 20:45:35,704 - ERROR - task.py - <module> - 33 - ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 20:50:10,992 - ERROR - task.py - <module> - 33 - ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 20:52:36,296 - ERROR - task.py - <module> - 33 - ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 22:02:33,708 - INFO - task.py - <module> - 33 - ZeroDivisionError('division by zero')
2022-06-08 22:03:40,093 - INFO - task.py - <module> - 33 - ZeroDivisionError('division by zero')
2022-06-08 22:18:48,675 - ERROR - task.py - <module> - 33 - division by zero
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 22:23:25,000 - ERROR - task.py - <module> - 33 - ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 29, in <module>
    x = (1/0)
ZeroDivisionError: division by zero
2022-06-08 22:25:05,848 - ERROR - task.py - <module> - 34 - IndexError('tuple index out of range')
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 30, in <module>
    print(x[4])
IndexError: tuple index out of range
2022-06-08 22:26:01,079 - ERROR - task.py - <module> - 34 - tuple index out of range
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 30, in <module>
    print(x[4])
IndexError: tuple index out of range
2022-06-08 22:33:55,743 - ERROR - task.py - <module> - 34 - tuple index out of range
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 30, in <module>
    print(x[4])
IndexError: tuple index out of range
2022-06-08 22:38:00,318 - ERROR - task.py - <module> - 36 - tuple index out of range
Traceback (most recent call last):
  File "C:/Users/91818/OneDrive/Desktop/Log/task.py", line 32, in <module>
    print(x[4])
IndexError: tuple index out of range
2022-06-08 22:40:13,440 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 22:45:47,616 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:54108/session/9c6d3c1fc75cfa9dc3afd6bc87dda45d/url {"url": ""}
2022-06-08 22:45:47,616 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:54108/session/9c6d3c1fc75cfa9dc3afd6bc87dda45d/url {"url": ""}
2022-06-08 22:45:47,631 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:54108 "POST /session/9c6d3c1fc75cfa9dc3afd6bc87dda45d/url HTTP/1.1" 400 1002
2022-06-08 22:45:47,631 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:54108 "POST /session/9c6d3c1fc75cfa9dc3afd6bc87dda45d/url HTTP/1.1" 400 1002
2022-06-08 22:45:47,633 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:45:47,633 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:46:03,979 - ERROR - task.py - launchBrowser - 88 - Message: invalid argument
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=102.0.5005.63)

2022-06-08 22:46:03,979 - ERROR - task.py - launchBrowser - 88 - Message: invalid argument
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=102.0.5005.63)

2022-06-08 22:49:44,430 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57970/session/67d4357cd60cf95f5abfb3e2c6e9ea52/url {"url": "https://www.cardekho.com/"}
2022-06-08 22:49:44,430 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57970/session/67d4357cd60cf95f5abfb3e2c6e9ea52/url {"url": "https://www.cardekho.com/"}
2022-06-08 22:49:46,771 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:57970 "POST /session/67d4357cd60cf95f5abfb3e2c6e9ea52/url HTTP/1.1" 200 14
2022-06-08 22:49:46,771 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:57970 "POST /session/67d4357cd60cf95f5abfb3e2c6e9ea52/url HTTP/1.1" 200 14
2022-06-08 22:49:46,773 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:49:46,773 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:49:49,724 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-08 22:49:49,724 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-08 22:50:01,208 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57970/session/67d4357cd60cf95f5abfb3e2c6e9ea52/window/maximize {}
2022-06-08 22:50:01,208 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57970/session/67d4357cd60cf95f5abfb3e2c6e9ea52/window/maximize {}
2022-06-08 22:50:01,448 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:57970 "POST /session/67d4357cd60cf95f5abfb3e2c6e9ea52/window/maximize HTTP/1.1" 200 51
2022-06-08 22:50:01,448 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:57970 "POST /session/67d4357cd60cf95f5abfb3e2c6e9ea52/window/maximize HTTP/1.1" 200 51
2022-06-08 22:50:01,453 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:50:01,453 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:50:03,635 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57970/session/67d4357cd60cf95f5abfb3e2c6e9ea52/element {"using": "xpath", "value": "//span[@class='used-cars-india0000']"}
2022-06-08 22:50:03,635 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57970/session/67d4357cd60cf95f5abfb3e2c6e9ea52/element {"using": "xpath", "value": "//span[@class='used-cars-india0000']"}
2022-06-08 22:50:03,673 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:57970 "POST /session/67d4357cd60cf95f5abfb3e2c6e9ea52/element HTTP/1.1" 404 1042
2022-06-08 22:50:03,673 - DEBUG - connectionpool.py - _make_request - 452 - http://127.0.0.1:57970 "POST /session/67d4357cd60cf95f5abfb3e2c6e9ea52/element HTTP/1.1" 404 1042
2022-06-08 22:50:03,675 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:50:03,675 - DEBUG - remote_connection.py - _request - 440 - Finished Request
2022-06-08 22:50:03,676 - ERROR - task.py - main_process - 157 - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)

2022-06-08 22:50:03,676 - ERROR - task.py - main_process - 157 - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)

2022-06-08 23:09:12,093 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:64240/session/a2f9ebb87186f5fef1128e0e6847fc3e/url {"url": "https://www.cardekho.com/"}
2022-06-08 23:09:46,610 - ERROR - task.py - launchBrowser - 88 - 'str' object has no attribute 'getMessage'
AttributeError: 'str' object has no attribute 'getMessage'
2022-06-08 23:11:20,558 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:56743/session/627800c4509119ec0d7648e4c14852fe/url {"url": "https://www.cardekho.com/"}
2022-06-08 23:11:51,831 - ERROR - task.py - launchBrowser - 88 - 'str' object has no attribute 'getMessage'
AttributeError: 'str' object has no attribute 'getMessage'
2022-06-08 23:16:00,773 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:53062/session/0457e379d564097196337d116eba79f6/url {"url": "https://www.cardekho.com/"}
2022-06-08 23:16:14,197 - DEBUG - remote_connection.py - _request - 388 - POST http://127.0.0.1:57915/session/88df7bbc4deb67fbcb4a66f6b22a16dd/url {"url": "https://www.cardekho.com/"}
2022-06-08 23:16:14,198 - ERROR - task.py - launchBrowser - 88 - 'str' object has no attribute 'getMessage'
AttributeError: 'str' object has no attribute 'getMessage'
2022-06-08 23:19:07,758 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:26:17,821 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:39:30,010 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:41:47,510 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:47:06,085 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:48:31,453 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:50:02,885 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:51:37,730 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:52:55,280 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:57:59,974 - ERROR - task.py - <module> - 36 - tuple index out of range
IndexError: tuple index out of range
2022-06-08 23:59:35,445 - ERROR - task.py - <module> - 36 - division by zero
ZeroDivisionError: division by zero
2022-06-09 00:01:39,011 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-09 00:01:39,843 - ERROR - task.py - main_process - 157 - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)

2022-06-09 07:54:26,305 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-09 07:55:17,214 - ERROR - task.py - main_process - 157 - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)

2022-06-09 07:56:55,064 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-09 07:57:02,809 - ERROR - task.py - launchBrowser - 88 - 'str' object is not callable
TypeError: 'str' object is not callable
2022-06-09 07:57:58,767 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-09 08:01:16,002 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-09 08:01:37,512 - ERROR - task.py - main_process - 157 - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)

2022-06-09 08:04:55,126 - INFO - task.py - launchBrowser - 84 - rul get loaded
2022-06-09 08:04:55,939 - ERROR - task.py - main_process - 157 - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@class='used-cars-india0000']"}
  (Session info: chrome=102.0.5005.63)

